config/routes.rb
Sistemapromotordevendas::Application.routes.draw do
  post "alterarsenha" => "funcionarios#alterarsenha"
  get "funcionario/reinit" => "funcionarios#reinit"
  
  get "status" => "conexao#status"
  get "listempresas" => "empresas#listempresas"
  get "listfuncionarios" => "funcionarios#listfuncionarios"

  get "consulta/:datainicio/:datafim" => "visita#consulta"
  

  get "funcionarios/login/:login/:senha" => "funcionarios#login"
  devise_for :users, :controllers => { :sessions => "sessions"}, :path_names => { :sign_in => 'login'}

  resources :empresas
  resources :visita
  resources :fotos
  resources :funcionarios

  root :to => 'visita#index'

end

app/models/empresa.rb
class Empresa < ActiveRecord::Base
  attr_accessible :nome_fantasia

  has_many :visitum

  before_save :uppercase_icao
  def uppercase_icao
    self.nome_fantasia.upcase!
  end
end

app/controllers/empresas_controller.rb
class EmpresasController < ApplicationController
  # GET /empresas
  # GET /empresas.json
  before_filter :authenticate_user!, :except => [:listempresas]
  layout 'app'
  def listempresas
    render json: Empresa.all.as_json
  end

  def index
    @empresas = Empresa.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @empresas }
    end
  end

  # GET /empresas/1
  # GET /empresas/1.json
  def show
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/new
  # GET /empresas/new.json
  def new
    @empresa = Empresa.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @empresa }
    end
  end

  # GET /empresas/1/edit
  def edit
    @empresa = Empresa.find(params[:id])
  end

  # POST /empresas
  # POST /empresas.json
  def create
    @empresa = Empresa.new(params[:empresa])

    respond_to do |format|
      if @empresa.save
        format.html { redirect_to @empresa, notice: 'Empresa was successfully created.' }
        format.json { render json: @empresa, status: :created, location: @empresa }
      else
        format.html { render action: "new" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /empresas/1
  # PUT /empresas/1.json
  def update
    @empresa = Empresa.find(params[:id])

    respond_to do |format|
      if @empresa.update_attributes(params[:empresa])
        format.html { redirect_to @empresa, notice: 'Empresa was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @empresa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /empresas/1
  # DELETE /empresas/1.json
  def destroy
    @empresa = Empresa.find(params[:id])
    @empresa.destroy

    respond_to do |format|
      format.html { redirect_to empresas_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/empresas_helper.rb
module EmpresasHelper
end

app/views/empresas/_form.html.erb
<%= form_for(@empresa) do |f| %>
  <% if @empresa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@empresa.errors.count, "error") %> prohibited this empresa from being saved:</h2>

      <ul>
      <% @empresa.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_fantasia %><br />
    <%= f.text_field :nome_fantasia %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/empresas/edit.html.erb
<h1>Editing empresa</h1>

<%= render 'form' %>

<%= link_to 'Show', @empresa %> |
<%= link_to 'Back', empresas_path %>

app/views/empresas/index.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Listagem</a>
  </li>
  <li><a href="#">Visualizar no mapa</a></li>
</ul>

<div class="section-menu">
  <table class="table table-striped table-bordered table-condensed">
  <% @empresas.each do |empresa| %>
    <tr>
      <th>Nome fantasia</th>
      <th></th>
    </tr>
    <tr>
      <td><%= empresa.nome_fantasia %></td>
      <td>
        <div class="btn-group">
          <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
            Ações
            <span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <!-- dropdown menu links -->
            <li><%= link_to 'Show', empresa %></li>
            <li><%= link_to 'Edit', edit_empresa_path(empresa) %></li>
            <li><%= link_to 'Destroy', empresa, method: :delete, data: { confirm: 'Are you sure?' } %></li>
        </ul>
        </div>
      </td>
    </tr>
  <% end %>
  </table>
</div>

app/views/empresas/new.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Cadastro de nova empresa</a>
  </li>
</ul>
<div class="section-menu">
<%= render 'form' %>
</div>

app/views/empresas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Nome fantasia:</b>
  <%= @empresa.nome_fantasia %>
</p>


<%= link_to 'Edit', edit_empresa_path(@empresa) %> |
<%= link_to 'Back', empresas_path %>