config/routes.rb
Sistemapromotordevendas::Application.routes.draw do
  post "alterarsenha" => "funcionarios#alterarsenha"
  get "funcionario/reinit" => "funcionarios#reinit"
  
  get "status" => "conexao#status"
  get "listempresas" => "empresas#listempresas"
  get "listfuncionarios" => "funcionarios#listfuncionarios"

  get "consulta/:datainicio/:datafim" => "visita#consulta"
  

  get "funcionarios/login/:login/:senha" => "funcionarios#login"
  devise_for :users, :controllers => { :sessions => "sessions"}, :path_names => { :sign_in => 'login'}

  resources :empresas
  resources :visita
  resources :fotos
  resources :funcionarios

  root :to => 'visita#index'

end

app/models/foto.rb
class Foto < ActiveRecord::Base
  attr_accessible :avatar, :hora, :visitum_id, :avatar_cache
  # validates_presence_of :avatar, :hora,:visitum_id, :message =>"false"
  mount_uploader :avatar, AvatarUploader
  belongs_to :visita
end

app/controllers/fotos_controller.rb
class FotosController < ApplicationController
  # GET /fotos
  # GET /fotos.json
  before_filter :authenticate_user!, :except => [:create]
  layout 'app'
  def index
    @fotos = Foto.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fotos }
    end
  end

  # GET /fotos/1
  # GET /fotos/1.json
  def show
    @foto = Foto.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/new
  # GET /fotos/new.json
  def new
    @foto = Foto.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foto }
    end
  end

  # GET /fotos/1/edit
  # def edit
  #   @foto = Foto.find(params[:id])
  # end

  # POST /fotos
  # POST /fotos.json
  def create
    @foto = Foto.new(params[:foto])

    # respond_to do |format|
      if @foto.save
        p 'true'
        render :json => "true".as_json
      else
        Visitum.find(@foto.visitum_id).delete
        p 'false'
        render :json => "false".as_json
      end
    # end
  end

  # # PUT /fotos/1
  # # PUT /fotos/1.json
  # def update
  #   @foto = Foto.find(params[:id])

  #   respond_to do |format|
  #     if @foto.update_attributes(params[:foto])
  #       format.html { redirect_to @foto, notice: 'Foto was successfully updated.' }
  #       format.json { head :no_content }
  #     else
  #       format.html { render action: "edit" }
  #       format.json { render json: @foto.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # # DELETE /fotos/1
  # # DELETE /fotos/1.json
  def destroy
    @foto = Foto.find(params[:id])
    @foto.destroy

    respond_to do |format|
      format.html { redirect_to fotos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/views/fotos/index.html.erb
<h1>Listing fotos</h1>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>id visita</th>
    <th>Avatar</th>
    <th>Hora</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fotos.each do |foto| %>
  <tr>
    <td><%= foto.visitum_id%></td>
    <td><%= image_tag foto.avatar, :class => "span3" %></td>
    <td><%= foto.hora %></td>
    <td><%= link_to 'Show', foto %></td>
    <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
    <td><%= link_to 'Destroy', foto, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<%= form_for @foto, :html => {:multipart => true} do |f| %>
  <p>
    <label>My Avatar</label>
    <%= f.file_field :avatar %>
    <%= f.hidden_field :avatar_cache %>
  </p>
  <div class="actions">
    <%= f.submit%>
  </div>
<% end %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Avatar:</b>
  <%= @foto.avatar %>
</p>


<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>