config/routes.rb
Sistemapromotordevendas::Application.routes.draw do
  post "alterarsenha" => "funcionarios#alterarsenha"
  get "funcionario/reinit" => "funcionarios#reinit"
  
  get "status" => "conexao#status"
  get "listempresas" => "empresas#listempresas"
  get "listfuncionarios" => "funcionarios#listfuncionarios"

  get "consulta/:datainicio/:datafim" => "visita#consulta"
  

  get "funcionarios/login/:login/:senha" => "funcionarios#login"
  devise_for :users, :controllers => { :sessions => "sessions"}, :path_names => { :sign_in => 'login'}

  resources :empresas
  resources :visita
  resources :fotos
  resources :funcionarios

  root :to => 'visita#index'

end

app/models/funcionario.rb
class Funcionario < ActiveRecord::Base
  attr_accessible :login, :nome, :senha
  has_many :visitum

  before_save :uppercase_icao
  def uppercase_icao
    self.login.upcase!
    self.nome.upcase!
  end
end

app/controllers/funcionarios_controller.rb
class FuncionariosController < ApplicationController
  # GET /funcionarios
  # GET /funcionarios.jso
  before_filter :authenticate_user!, :except => [:login,:listfuncionarios, :alterarsenha]
  layout 'app'
  def alterarsenha
    @id_funcionario = params["cod"]
    @senha_nova = params["senhanova"]

    @funcionario = Funcionario.find(@id_funcionario)

    if @funcionario 
      @funcionario.senha = @senha_nova
      if @funcionario.save
        p "true"
        render :json => "true"
      else
        p "false"
        render :json => "false"
      end

    else
      p "false"
      render :json => "false"
    end

  end
  def listfuncionarios
    render json: Funcionario.all.as_json
  end
  def login
    # params["funcionario[login]"];
    # params["funcionario[senha]"];
    @funcionario = Funcionario.where("login = '#{params["login"]}' and senha = '#{params["senha"]}'")

    if @funcionario.size > 0
      render :json => @funcionario[0].id.as_json
    else
      render :json => "false".as_json
    end
  end

  def reinit
    # @funcionario = Funcionario.find(params[:id]);

    # @funcionario.init_senha

    # if @funcionario.save
      render :json => "Ação realizada com sucesso".as_json
    # else
      # render :json => "Ocorreu uma falha, tente novamente".as_json
    # end

  end

  def index
    @funcionarios = Funcionario.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @funcionarios }
    end
  end

  # GET /funcionarios/1
  # GET /funcionarios/1.json
  def show
    @funcionario = Funcionario.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/new
  # GET /funcionarios/new.json
  def new
    @funcionario = Funcionario.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @funcionario }
    end
  end

  # GET /funcionarios/1/edit
  def edit
    @funcionario = Funcionario.find(params[:id])
  end

  # POST /funcionarios
  # POST /funcionarios.json
  def create
    @funcionario = Funcionario.new(params[:funcionario])

    @funcionario.senha = "padrao"

    respond_to do |format|
      if @funcionario.save
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully created.' }
        format.json { render json: @funcionario, status: :created, location: @funcionario }
      else
        format.html { render action: "new" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /funcionarios/1
  # PUT /funcionarios/1.json
  def update
    @funcionario = Funcionario.find(params[:id])

    respond_to do |format|
      if @funcionario.update_attributes(params[:funcionario])
        format.html { redirect_to @funcionario, notice: 'Funcionario was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @funcionario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /funcionarios/1
  # DELETE /funcionarios/1.json
  def destroy
    @funcionario = Funcionario.find(params[:id])
    @funcionario.destroy

    respond_to do |format|
      format.html { redirect_to funcionarios_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/funcionarios_helper.rb
module FuncionariosHelper
end

app/views/funcionarios/_form.html.erb
<%= form_for(@funcionario) do |f| %>
  <% if @funcionario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@funcionario.errors.count, "error") %> prohibited this funcionario from being saved:</h2>

      <ul>
      <% @funcionario.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br />
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :login %><br />
    <%= f.text_field :login %>
  </div>
    <%= f.submit nil, :class=> "btn btn-primary"%>
<% end %>

app/views/funcionarios/edit.html.erb
<script type="text/javascript">
var reinit = function(){
	$.getJSON("http://192.168.1.11:3000/funcionario/reinit",function(response){
		alert(response)
	});	
}
</script>
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Edição</a>
  </li>
</ul>
<div class="section-menu">
	<%= render 'form' %>
	<%= link_to 'Cancelar', funcionarios_path, :class=> "btn" %>
	<button onclick="reinit()" class="btn btn-warning">Reiniciar senha</button>
</div>

app/views/funcionarios/index.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Listagem de funcionários</a>
  </li>
</ul>
<div class="section-menu">

<table class="table table-striped table-bordered table-condensed table-hover">
  <tr>
    <th>Cod</th>
    <th>Login</th>
    <th>Nome</th>
    <th></th>
  </tr>

<% @funcionarios.each do |funcionario| %>
  <tr>
    <td><%= funcionario.id %></td>
    <td><%= funcionario.login %></td>
    <td><%= funcionario.nome %></td>
    <td>
      <div class="btn-group">
        <a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
          Ações
          <span class="caret"></span>
        </a>
        <ul class="dropdown-menu">
          <!-- dropdown menu links -->
          <li><%=link_to 'Visitas', funcionario%></li>
          <li><%=link_to 'Editar', edit_funcionario_path(funcionario)%></li>
        </ul>
      </div>
      <!-- 
      <%= content_tag :i, (link_to ' Visitas', funcionario), :class => " icon-th-large" %> 
      <%= content_tag :i, (link_to ' Editar', edit_funcionario_path(funcionario)), :class => "icon-remove" %> 
       -->
      <!--  
      <%= content_tag :i, (link_to ' Desligar', funcionario, method: :delete, data: { confirm: 'Are you sure?' }), :class => "icon-remove-sign" %> 
       -->
  </td>
  </tr>
<% end %>
</table>
</div>

app/views/funcionarios/new.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#">Cadastro de novo funcionário</a>
  </li>
</ul>
<div class="section-menu">
<%= render 'form' %>
</div>

app/views/funcionarios/show.html.erb
<ul class="nav nav-tabs">
  <li class="active">
    <a href="#"><%= @funcionario.nome %></a>
  </li>
</ul>
<div class="section-menu">
<h3>Visitas</h3>

<table class="table table-striped table-bordered table-condensed">
  <tr>
    <th>id</th>
    <th>Empresa</th>
    <th>Data hora inicio</th>
    <th>Data hora fim</th>
    <th>Latitude</th>
    <th>Longitude</th>
    <th></th>
  </tr>

<% @funcionario.visitum.each do |visitum| %>
  <tr>
    <td><%= visitum.id %></td>
    <td><%= link_to visitum.empresa.nome_fantasia,  visitum.empresa%></td>
    <td><%= visitum.data_hora_inicio %></td>
    <td><%= visitum.data_hora_fim %></td>
    <td><%= visitum.latitude %></td>
    <td><%= visitum.longitude %></td>
    <td>
        <%= content_tag :i, (link_to ' Exibir', visitum), :class => " icon-th-large" %> 
        <!-- 
        <%= content_tag :i, (link_to ' Editar', edit_visitum_path(visitum)), :class => "icon-remove" %> 
        <%= content_tag :i, (link_to ' Desligar', visitum, method: :delete, data: { confirm: 'Are you sure?' }), :class => "icon-remove-sign" %>
         -->
    </td>
  </tr>
<% end %>
</table>
</div>

<p id="notice"><%= notice %></p>